# Generated by Django 4.0.6 on 2022-07-20 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_photo')),
                ('phone', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=150)),
                ('education', models.CharField(choices=[('SSCE', 'SSCE'), ('Dip', 'Diploma'), ('BSc', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BEng', 'Bachelor of Engineering'), ('MSc', 'Master of Science'), ('MBA', 'Master of Business Administration'), ('Dr', 'Doctorate Degree')], default='BSc', max_length=33)),
                ('resume', models.FileField(null=True, upload_to='resume_bank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
