# Generated by Django 4.0.6 on 2022-08-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_skills_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.applicant')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter')),
            ],
        ),
    ]
