# Generated by Django 4.0.6 on 2022-08-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_selectedcandidate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectedcandidate',
            unique_together={('recruiter', 'applicant')},
        ),
    ]
