# Generated by Django 4.0.6 on 2022-08-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_selectedcandidate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedcandidate',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SelectedCandidate_applicant', to='users.applicant'),
        ),
        migrations.AlterField(
            model_name='selectedcandidate',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SelectedCandidate_recruiter', to='users.recruiter'),
        ),
    ]
