# Generated by Django 4.0.6 on 2022-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_skill_alter_applicant_image_delete_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=255),
        ),
    ]
