# Generated by Django 4.0.6 on 2022-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_skill_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=255),
        ),
    ]
