# Generated by Django 4.0.6 on 2022-08-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='applicant',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level')], default='Entry Level', max_length=100),
        ),
    ]
