# Generated by Django 4.0.6 on 2022-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_skill_experience_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(choices=[('SSCE', 'SSCE'), ('Diploma', 'Diploma'), ('Bachelor of Science', 'Bachelor of Science'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bachelor of Engineering', 'Bachelor of Engineering'), ('Master of Science', 'Master of Science'), ('Master of Business Administration', 'Master of Business Administration'), ('Doctorate Degree', 'Doctorate Degree')], default='Bachelor of Science', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='tools',
            field=models.ManyToManyField(blank=True, default='Google Workspace', to='users.tool'),
        ),
    ]
