# Generated by Django 4.0.6 on 2022-08-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tool_alter_applicant_education_applicant_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level')], default='Entry Level', max_length=100, verbose_name='Experience Level'),
        ),
    ]
