# Generated by Django 4.0.6 on 2022-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_applicant_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level')], default='Entry Level', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='users.skill'),
        ),
    ]
