# Generated by Django 4.0.6 on 2022-08-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_applicant_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(choices=[('SSCE', 'SSCE'), ('Diploma', 'Diploma'), ('Undergraduate Degree', 'Undergraduate Degree'), ('Postgraduate Degree', 'Postgraduate Degree')], default='Undergraduate Degree', max_length=255),
        ),
    ]
